import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"
import services from "../services.json"

export default function Home() {
  console.log("services", services)

  return (
    <div className={styles.container}>
      <Head>
        <title>Elements Web Development Services</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a>Welcome to Elements Web Developmet Services!</a>
        </h1>

        <p className={styles.description}>Need Help with...</p>

        <ul className={styles.grid}>
          {services.map(service => {
            const { id, title, description, image, price } = service
            return (
              <li key={id} className={styles.card}>
                <a href="/" className={styles.card}>
                  <h2>{title}</h2>
                  <p>{description}</p>
                  <p>{price}</p>
                </a>
              </li>
            )
          })}

          <li className={styles.card}>
            <a href="/" className={styles.card}>
              <h2>Sell your products online</h2>
              <p>Website Redisgn and Build</p>
            </a>
          </li>
          <li className={styles.card}>
            <a href="/" className={styles.card}>
              <h2>Website Performance Issues</h2>
              <p>Discover and deploy boilerplate example Next.js projects.</p>
            </a>
          </li>
          <li className={styles.card}>
            <a href="/" className={styles.card}>
              <h2>Get a new webiste/ Redisgn Website</h2>
              <p>Lets get you up and runnig with your own website or blog</p>
            </a>
          </li>
        </ul>
      </main>

      <footer className={styles.footer}>
        <a href="/" target="_blank" rel="noopener noreferrer">
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
